version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
    open-pull-requests-limit: 10
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
