project_name: mkgoprj
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: .
    ldflags:
      - -s -w -X github.com/nao1215/mkgoprj/v2/internal/cmdinfo.Version=v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - maintainer: Naohiro CHIKAMATSU <n.chika156@gmail.com>
    description: mkgoprj - Golang project template generator
    homepage: https://github.com/nao1215/mkgoprj
    license: Apache License 2.0
    formats:
      - deb
      - rpm
      - apk
