// This package is generated by ubume command.
//
// If you publish this module on GitHub etc., please write down the 
// application description in this file. When your package is published
// to "https://pkg.go.dev/", the contents of doc.go will be automatically
// listed as an overview on the pkg.go.dev.
package sample
